name: 'GitPortalCheckChanges'
description: 'Verify no local KMP changes'
author: 'Touchlab'
inputs:
  sshPrivateKey:
    description: 'Private SSH key to register in the SSH agent'
    required: true
  kmpModule:
    description: 'KMP module to check for changes'
    required: false

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.kmpModule }}
    - -pb ${{ github.event.pull_request.base.ref }}
